title: "【Next.js×Firebase】リアルタイムChatアプリの実装"
summary: |-
  これからNext.jsを学習したい、開発してみたいという人向けです。
  Firebase AuthenticationとFirestore、Recoil、chakra-uiを使用した開発です。
  また、vercelでのプロジェクト公開手順までを解説します。

  この1冊でNext.jsを使ったwebアプリの実装から公開までを学ぶことができます。
topics:
  - "firebase"
  - "nextjs"
  - "vercel"
  - "recoil"
  - "chakraui"
published: false
price: 200
toc_depth: 1
chapters:
  - "fe697a"
  - "d424fb"
  - "7b42f2"
  - "9aa279"
  - "0f878e"
  - "e72de4"
  - "f500c3"
  - "fabd2a"
  - "2cdbcf"
  - "2012b5"
  - "00bf1c"
  - "50dcd8"
  - "561890"
  - "e7a90c"
  - "ff2101"
  - "fb7d51"
  - "3b347e"
  - "adb561"
  - "bbc0c6"
  - "f851c8"